# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:NO7rnjM21tZtit+ReLAFPVEq8F4xkDiZu0ajzZLRjev8YFvgrjlehLgje1j2Ywd5aTKQZAc8vA2EI7OjXQTFAqO+WZYzVbfPa/L/OxI/YZRViCcak3VeJTJqgLc5IYBOXtUpxF+nwuWVui7bPlH6yAMj1L7JHeOR/K8NTjh+sO1J/il45kyglIp17gYny1msvhon/k5HS7znOs94WBoua1xNbXVM0YkpJFP2fW3KsVqBfhTx0x3PWHzyXLnRweBfGTskXeeQGfUIJfBzVavfkAzp9pOCMQdT9hveazQwkArlp+8kdeNdFrmwSLGYRZbmnp9EK74sY2pturkzA0eSd5T0C7ocLxoNxiNuiwJ2Q/gqgYkfHR46x3N8383MEnSyLevOu9T/jUkNE2YfqtylDtjjdg6zhJjy1mIErl984PjTxnQKzVoqGHQQM/L+wLD1wHJAiHGNcj1b4emhlmfqXjxicrujZD3WtpTDEdCR4uyAcaEwNU/rl23WPQLZ3cKqRXoycfRq/HGxtd0Yw8r65Np13Bt0r52doDC59JA971xGYSPYusiwraodUFkDB8XS5qhl9N7+2dFCqmKaqEoaAX/UoxafYxkmfptuZ/SHhWnvZHMDXxz/IjuH4LzghL9/D7uswGvlnd7hH6yaAjpYCY7iu6aM+1qul3SLXxkFMKvsKP/H2Gt/0r8JTzMvmO3p33TzYUTqtmvloVmqvEsmYJNGGgc3Onx4tQBXaxzjis10rJVEdTSlCnPUo+q22rv7enkV1cqzFgSfUyl1bz/x+CS9epizi0mlozJvFUcEb9IjOXty2LZDw0+v3fdwTcAk/xofllvxHJh7EuFKWvWYAs2YFHKJmOt1+5LLhbFhQBMLhCoDqvREiLiu0WbndzSIGBu6Ge3/fmVMjP2F+y7lh2cQpncLT0sAVIyGGFuPED9S9LATS12b76yCrEqmfF0MCPNAqZQBWeJCmWzmMerjz31dl50AMFtpRK5hVSTyMFI1shxTmkYG/HwvxFft5DnUeLVFNGuEtv3WXatPumvOtmkVvjDdqJO5gOAtqslca0ebjT6wksImss8Q3TD0V3VSeJ8Scy4TQh1sxfJk96P3TbHVceLOLwaTv0J3AJ67MSBkyqJb2OyUJytk+ERP79iZOAu/XjaMCKFpSLMRWBI5OtHzCoQi2EI0XQMDNRP5RerpFnRPCERpwVOqyP8FO9Op3cFBtC8BYLaDcszUJviv04DkslcPEzvmuBSGQ6fZO1EnWW4lUOFIfmhIBtPnTay58JFJyHTEt8yEHYeTA0MtkPVls5tGdIeo3fBERNzdvlqsO+4I0Jc/W5RR3vqR+NtbvkIyf0zMC5rH/MhKy1UX61LvznMmXuITdKtEr0f8Msarz4EpA6wHKm5PaU1VqRB9YIMJco45GjMVgPwW9cqB4wYYxpCUMy8QJftB05+hxACEpwj9cGTEcJvyTFX4gIA81LhiaqOhdug2r681/jdWIehne9UVm+AWtwcVXy7386h2H3pye+OGu4WxEQOoPCSgj/Gq27GGKelq2anwjmMzuhKu4NZ8N6HLuR0NmiKoZQ4VHIWeDXZIKOaYKKIPekIliuagbWvrsMXBs/zJbZ25EJ6XJrbfyLYUHd1RgxprUouijdlg2VU7kpY2/Hhy26kNX115gfngyl+XwY/Xp8Hd5GNBLc6X4TMYFgkT/Yp30sU+j5f6wiOiDYsquW/RCo/7XU6miRSgHlmnt6lD7NuI4KSx/i0HedIAUMsmxRUZwohLTuNU6XPfwBLv0f76CUU7vRAO0s1whDcRmrepkr0fmhIHSDyXDQCprEO2bMDCNAOEXRx+rjLX5K2Kx8P+HVRHwwK0S55i+oLRQL5tK8R1bFF6rt8BZieJ9p34X0gh9/3H+fas5II1fpoYLHlrRFmcdr7kseg1frYvfNHTbPtG+AbLF5c5HFf/1ILfAXhSjJ1bbrNPy3N34orA5lg2Igj8OATeakC3wLGjRkV2vABMEj416nP5qL5SGYD8+B4cvB5+lsxt,iv:KQN5XOXJfbCNGnbNQtdEhZ3d8HehSuHo+iTzrzngUck=,tag:LINQ7KlOoUf1zv0Jj571PA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vector-values
    namespace: logging
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-15T17:19:01Z'
    mac: ENC[AES256_GCM,data:l64KrQwnDV9gzVLEpTBX3Yp4KpXM2p8mHx/OUywQ+HPbN6bRE9GTyOOFp9IT8I1WVYFSOpkMEcoiFEpYiaDkwNoKksgcPNFXoUkljPFL608Et63vKHgb2H+P7yzH69cYmXmBJZCNO5Wsd68SGmKhS96wL+vuhSveBUD/nIzyqo0=,iv:4WYoroIir63jfWKYWqn6oDX5xmIiOeqKYGEtpbI7lok=,tag:60f6pLDeCZnhuglbST8PZg==,type:str]
    pgp:
    -   created_at: '2021-05-15T17:19:01Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1C6tKCBeleKARAAQtmXYoJk93zaMzZ7/VXhdNCNFWBO8KQpThgwNTesJRrU
            907+7768UUsovrpHD08SzdGJ857XeoVVVCLMjmWidi47tdE0iA2WWcOhvx1bfOPg
            7c2CNkySzNJZicy2TL3NYRH3eAQb/kPWuj0qfImiYEHrLR5ryy8bcEiLn38rS/sK
            oVQaysWF7lunHlr5htvYuqpZwqgnfZZvzrpwSuy+ufdncNODBuxizWzTKE2g8HT5
            0pumxixy/gMl5gfidzHeml+rlTcQMbJf6GOxLi0jyNi89wQPwHvLWZWpqDbOaj0r
            lZi0EGcJ7smbLGYfcMWI8/ny7X12DlNMXXbg3Ad3H7aNEYpxFUlaFLvPWH2I3rVV
            9Ll5oqQFBbq+jTPBg1W8KRMjn+fiJUDjAFMZzN3gV3UtHbCZJetwDyqGDELj32oC
            fXoXHmcUgEbcei4VZenWGBEQqyTeGMlBhtin6h3lwVAgi8VhgtfvdIj5K+qbc/zU
            6KAZePO5zcsqriT7cGuI5oCn3H5iTgiPeQ1gOD+yL6MNlLMSSMrr4ABsumkJkVxO
            xd7z6dTyNeiQY8dWOleudqq37NwEMvXQ2zEoDnfVPeK5+DcXmTAZbh1Yb9ePVKM6
            tMZYKllPYskAUDNDiDKlvFZMpNNIMxCSeuOslY7lH9aHNAwV3HbNJBmP1POB6YXS
            4AHkkzZJVMCjY2P4D381dB33ruFAe+AN4JjhaNTgHeLSkiXi4OHlOOfx3L6RJVAm
            +aEgTmRW5fb3P1FdYsncN7FFEl2VsRHg2OS3I6Qd6frO/aeg1XReN9RF4v7QLMrh
            +EsA
            =9G+G
            -----END PGP MESSAGE-----
        fp: 82515583D0225FABE4F4FC7874420B8A43DCF894
    encrypted_regex: ^(data|stringData)
    version: 3.6.1
