# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:ZrI7olCz+rYc85MuiPl+7KtsO/DMefiakS3jllF0e785HfS0/w5N4Peqcew1uu8ozJq384jeNpcyZ5k9jngRKUcShreqP8iRpnj5rmHS1xObNnOFjYZoUJGhBT3wY2InKTmkMAAevwruxNa+KiwpoqaljeL3KpWEhXobMSjJvouuVO7r1urrlOH7IHnIFxxlr160GnQVbPAxI47F0Ep0ZKfVZICPwwPuPvOsvXNQedZdVsKgkslTvfph+uOTesdy1sYm8YDXGiatUPaHp0sxBH5kaQaex7Nzf6MNq7Iar22PUkpCi+dMM5FyquPOMJLmZH2yQHYl5LlB/ZVaFtstStjLhLOIyi3yBLRX7usJZIUl5A3uGJqJLH2B/5q5vyxuKr6fcQdvNeY4SWB2iuoii4aNkabfKsuDfCfE7msn+G4oVex5+/APSxrKlIM9tvpvevKKPIVKfGxm0chNaQW1OxUjtb57GsCVfPFoqO6RZ6O8eClTTuPi5zsqr1H69tiGrG4z7KU5dT3Im95XILjJ7e7+OsWshPoAzkTH4P7zTeFjDn7Irhe3FmyLnN21p1V8C/h5zXjsFRTluLwj8t2imZPOF497ICN4ggk1qNeMBJbT2Tx9Ee/NVvImiD57r5Vn2m5eGWHN+uaII/4kdJXpSNK88iW8tB5tdg2pirQSI5kwKEynLSgwt1ib2aI+D7tCjM7BXcoyepFZfJQib4GwyjME4Sg463IRfnIYOBRWMM2bWmc+IV/Civh8b1j60FIPzuGP+MwnTxx0O7gJuUglLTcnFIS/LqcrIB0uGgJmmEszLU+FFUg2Eq5fLFxHZixzZYh8BxCsa1pyQrM9nV+M52GtDtgxAYAds5HvdiZi2L4WTVg4ufvJ8/TU2FY6QdWcFEtBWGflMr5QcmOqVdn1H2zqjWI2Yo+62BI2egQctM2pBUyMakvedPY9TzwZko58LtYrVH3QzIIVPI4zxQNHvRM/s5aAokM3n/+CJOIMucmTrKKao+vz6zWJSDT8luT6OFmW5zovRV0cCTOCiPI3kkKDeYSWZvAml6Bouv95giOWWKBYgdWxkT3dBVaxtVTrTgSQi8IKr1M16MK6Iy1PpkHiWR0r5queE5+zxzY1BaRqV+vX/znvc5gmouw76o9ckKu59lCqz8tXXFJ0X471GXIrJACNujcVpIcIFtrqtIBtBAu0/sAH/cz6yWVOb/Urv2lnAhq8cJ87Vu8tEizcuh2zTLsAByDWnvtkntS5E9E276oEAttha7ZUBcQrNBCjiZj97rz+1ZvcLfGgDPTPGq7E/C5c/quhe7ymcKANBt3kKOZ8wvB7XztYA3S88pOlmnkPVQfaJkPkux/qf+Q8K32kLs0jYa3I0qOIvbSW9ExthgX4eoURX7+LrefnNT0tEmhC0+FiRZYHUyXSaKgBBk8mBszg5mwYutA8vfiOQ8z3E/s8wCcstjLM2YPGPC7lvv2OnuywUUN4ebpQharlwCwdWLQJfOQY7o3+oIMUKfou2xpYFX2fD7rgLu+WpYz0V1H99L0cHG5BWCfW6Oquc5lDNvpi0owc4ugAckKHeAtNLC0imZDqOYBmUQ/7ToXttOZSlqThZWyHc+0jsrovNpzL44Kr0JKBhQeztIqIT7ygSRgLqX2d+wYfKHmwxyYh9lV32qzkRDtJJ68NaRh6WSTkI193S3EVENHq6B3D33B65pcxdcvGiYdBaHSQHf7skkyMqqsje7fzlE5WqywbEfTlFDXdh5pmIwH4oTpK9mMu8EaKKWLzJKyEw1S0+JKfE504Qs7ntPifTANTXVDHY5T6BJKTY5v+TdC3Jxj4IKdvvXNH8eiWWo1Tsmc6Ro8iWAvFzTqEeVCwXtS23GS0n8zqheU93+k+oQ12Dlh5jg8WMr5v05Eq4a03lHtl4B4wmOMuBxuc9nt9c8sxxGpvAc6xOMANwvhivBFEudO/2aEx2BJui4DnzyKVqyb24uf8ZgOpcjJ+It2oZ89vaglNsYaD7ZR5WZlOmB8GSP4XO8076AP9NnJ9I4AQwiaiNLqXaMabDRfWDwnqjYftV51rs5zwCJEwKxQPhTkSAOnYBx0PmUUx3q2rr8CjFRc92z4HuxwmI3MbDTEQvvQ+rpJoZC9ong8h1I6nCbET0TPSqnOzJlxww8An/jSYyMFyO8FaGaej3+KeXLQaUfptVLhDdDVRmBv2UZtCNLSVzpaQuxQ/lFpb2R8QWUAVEbr8G4GYYkz776nv6h2rsWB0tgMDvdISYHB7vnAv7Bv8CswJAD+1L4tQQg2DRNPcCYTU34tUZ91lCQtHyG2yYCNZSuHIQUdhlvKZ7DnsBAqxmEj2H1lNZ0DQdHaoiHZ8U9WDEmOTkqNwj/l26Ib9wqGmqnfqB7EMji2HJwP5qa4Mk/zBasFSG3qfMg3eTZuRV0wgpngIgpcM+/o4eIqnGn9i,iv:UQUEwJm4J9CFW/xvADnRvQz6V1WEu3Xdt7N+II9pGu8=,tag:C01txBh3VOQmVHd2OTB08w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vector-values
    namespace: logging
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-24T05:51:26Z'
    mac: ENC[AES256_GCM,data:H3+aLzxg6NjMYfKMnj2Fyymu6x/+i2I0vkVk3fwCObzOLI35zTw0WT2uqSZ1MtzdTtO8q1+B/xYK6RuAu8yiLOxNwD9xuBxLVyWblijQTeHGvOKOrvOPPTvQO2cqwcY707FLUGcYCPQDirWIB3xmcI0tjcOma0AzaR1yyFzMYtY=,iv:W3SwI+upGxBQmkEzFnZNR8CqhC0Oxh4nf9Utzu5sh1c=,tag:XMFKw/aR/yjzekJ8HXbZcg==,type:str]
    pgp:
    -   created_at: '2021-06-24T05:51:26Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1C6tKCBeleKARAAHGptzfy0oS96EMJ4ca13Ad2RmQouBll0bSugFkaoa0e7
            77qSHQoVfaOsJ6Z4mQJ4hElR9Wr6hpNLFqj47P9xngyhZYMQl03mXip/OYrM1AUg
            HWPJGiHpL14mMArYslu8yWVPlWKjazC9bY9C59kMotiw7RNL1gjAZjKJJx0gAdPq
            kJQ36q45e5EhRz6fQgzGlvDl+BKZKqwz3Ay9LURZE/P+kTdyjbjH51EGuRpBhTwE
            bt+Lvh5qvzDckUJajQPwDFE8PHdJcMRKLK+84Txemnswh5CLv1G8fcxCAUAcnn9l
            saGgFRhCWpcUs+v6r8zwDyDO4/koho4iuKgCZ22c9pB6PujdGPx2TAw77mykxoMU
            6k5Zk7m+DUqFi5sE6/uQypXD1VlB5T/khpv84D1XAppOaGrwu7kwwOI+NQRI9Byr
            QBdEQx9QWe4jTK5xXwMKF4+awzN1tEf5DKgVvanMwiTsMLstBsbmd7DmOHFf5xqm
            hQfUuVRmjFfiyVMxKFqhCHO+jVGv6vMSmHPXysfsy644rPVzv8rXx90sIitax1Hi
            ByA8Lf0ZjOhs5AO6HvyjPc3CO6FJNFwtdnQrYIHF21L78NjnCvL26KWhYOZpH8kZ
            7wCRCKbgK15HAsdTgQexPFvDh7CE3NFGpFNgW/rpZ50UL8mP+NAH2CpA8OTJFxnS
            4AHksSWWEpA6MpkdbPNnoYML6OGG0uD/4G7hcZjg7eK4DeZx4LHlhEjuyDTLEVtT
            PKPdbe0ab5TpPsKnqy0RZJxnF0//PD/gUOT1UXVFEJIZGs1VDjUtxpqB4kyy3mrh
            6K0A
            =hk7x
            -----END PGP MESSAGE-----
        fp: 82515583D0225FABE4F4FC7874420B8A43DCF894
    encrypted_regex: ^(data|stringData)
    version: 3.6.1
