---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: chaos-mesh-crds
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/prod/chaos-mesh/chaos-mesh-crds
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    # For ServiceMonitor CRD
    - name: kube-prometheus-stack
    # See: https://github.com/chaos-mesh/chaos-mesh/pull/1200
    - name: chaos-mesh-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/prod/chaos-mesh/chaos-mesh
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: chaos-mesh
      namespace: flux-system
