---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    # For ServiceMonitor CRD
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/prod/storage/velero
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: velero
      namespace: flux-system
