---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  values:
    store:
      enabled: true
      persistentVolumeClaim:
        name: thanos-store-data-volume
        spec:
          #  storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
      resources:
        limits:
          cpu: 300m
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 400Mi

    query:
      enabled: true
      http:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: 'letsencrypt-prod'
            nginx.ingress.kubernetes.io/auth-url: https://forwardauth.gcp.portefaix.xyz/verify?uri=$scheme://$host$request_uri
            nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.gcp.portefaix.xyz/?uri=$scheme://$host$request_uri"
          hosts:
            - thanos.gcp.portefaix.xyz
          tls:
            - secretName: thanos.gcp.portefaix.xyz-tls
              hosts:
                - thanos.gcp.portefaix.xyz
      resources:
        limits:
          cpu: 800m
          memory: 1Gi
        requests:
          cpu: 300m
          memory: 500Mi
      stores:
      #  - "dnssrv+_grpc._tcp.<service>.<namespace>.svc.cluster.local"
      - "dnssrv+_grpc._tcp.kube-prometheus-stack-prometheus.monitoring.svc.cluster.local"


    compact:
      enabled: true
      persistentVolumeClaim:
        name: thanos-compact-data-volume
        spec:
          # storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
      resources:
        limits:
          cpu: 300m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi

    bucket:
      enabled: true
      http:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: 'letsencrypt-prod'
            nginx.ingress.kubernetes.io/auth-url: https://forwardauth.gcp.portefaix.xyz/verify?uri=$scheme://$host$request_uri
            nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.gcp.portefaix.xyz/?uri=$scheme://$host$request_uri"
          hosts:
            - thanos-bucket.gcp.portefaix.xyz
          tls:
            - secretName: thanos-bucket.gcp.portefaix.xyz-tls
              hosts:
                - thanos-bucket.gcp.portefaix.xyz
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 300Mi

    rule:
      enabled: false

    sidecar:
      enable: true
