# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: Portefaix
site_author: Nicolas Lamirault
site_url: https://www.portefaix.xyz
site_description: >-
  Kubernetes

copyright: Copyright &copy; 2020 Nicolas Lamirault

# repo_name: nlamirault/portefaix
# repo_url: https://github.com/nlamirault/portefaix
# edit_uri: ""

# theme:
#   name: material
#   logo: _files/flux-icon@2x.png
#   language: en
#   palette:
#     primary: indigo
#   custom_dir: mkdocs/
#   features:
#     - navigation.tabs

# Configuration
theme:
  name: material
  custom_dir: mkdocs

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - toc.autohide
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    # - navigation.instant
  highlightjs: true
  hljs_languages:
    - 'yaml'
    - 'json'
    - 'bash'
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  # icon:
  #   logo: logo
  logo: img/portefaix.png

docs_dir: docs

extra_css:
  - _static/custom.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nlamirault
    - icon: fontawesome/brands/github
      link: https://github.com/nlamirault/portefaix

plugins:
  - search

markdown_extensions:
  - admonition
  - meta
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      highlight_code: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Infrastructure:
      - Local: infrastructure/local.md
      - Google Cloud Platform: infrastructure/gcp.md
      - Amazon AWS: infrastructure/aws.md
      - Microsoft Azure: infrastructure/azure.md
      - Alicloud: infrastructure/alicloud.md
  - User:
      - Secrets: user/secrets.md
      - Gitops: user/gitops.md
      - New Cluster: user/new.md
  - Stacks:
    - Certificates:
      - Cert-Manager: stacks/cert-manager/cert-manager.md
      - Letsencrypt: stacks/cert-manager/letsencrypt.md
    # - DNS:
    #   - External DNS: stacks/dns/external-dns.md
    - Flux:
      - System: stacks/flux-system/system.md
      - Monitoring: stacks/flux-system/monitoring.md
      - Sources: stacks/flux-system/sources.md
      - Notifications: stacks/flux-system/notifications.md
    - Identity:
      - Pomerium: stacks/identity/pomerium.md
    # - Ingress Controllers:
    #   - Default Backend: stacks/ingress-controllers/default-backend.md
    #   - Nginx Ingress Controllers: stacks/ingress-controllers/ingress-nginx.md
    # - Kube-System:
    #   - Metrics Server: stacks/metrics-server/metrics-server.md
    #   - Sealed Secrets: stacks/sealed-secrets/sealed-secrets.md
    # - Logging:
    #   - FluentBit: stacks/logging/fluentbit.md
    #   - Promtail: stacks/logging/promtail.md
    #   - Loki: stacks/logging/loki.md
    - Monitoring:
      - Prometheus Operator: stacks/monitoring/prometheus-operator.md
      - Prometheus: stacks/monitoring/prometheus.md
      - Thanos: stacks/monitoring/thanos.md
      - Alertmanager: stacks/monitoring/alertmanager.md
      - Kube State Metrics: stacks/monitoring/kube-state-metrics.md
      - Node Exporter: stacks/monitoring/node-exporter.md
      # - Pushgateway: stacks/monitoring/pushgateway.md
      # - Blackbox Exporter: stacks/monitoring/blackbox-exporter.md
      - Grafana: stacks/monitoring/grafana.md
    # - Reporting:
    #   - Kube Resource Report: stacks/reporting/kube-resource-report.md
    #   - Polaris: stacks/reporting/polaris.md
    # - Security:
    #   - Gatekeeper: stacks/security/gatekeeper.md
    - Storage:
      - Velero: stacks/storage/velero.md
  - Troubleshooting: troubleshooting.md
  - Roadmap: roadmap.md
  - Reference: reference/reference.md
  - Glossary: reference/glossary.md
  - Contributing: CONTRIBUTING.md
