[tool.poetry]
name = "portefaix"
version = "0.1.0"
description = ""
authors = ["Nicolas Lamirault <nicolas.lamirault@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
# diagrams = "^0.17.0"
diagrams = { git = "https://github.com/mingrammer/diagrams.git", branch = "master" } #, tag = "v0.17.0" }
mkdocs = "^1.1.2"
mkdocs-material = "^7.0.0"
mkdocs-diagrams = "^1.0.0"
black = "^20.8b1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
