---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: identity
spec:
  interval: 5m
  chart:
    # renovate: registryUrl=https://helm.pomerium.io
    spec:
      chart: pomerium
      version: 14.0.0
      sourceRef:
        kind: HelmRepository
        name: pomerium
        namespace: flux-system
  releaseName: pomerium
  targetNamespace: identity
  values:
    metrics:
      enabled: true
      port: 9090
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

