# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: chaos-mesh
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.chaos-mesh.org
      chart: chaos-mesh
      version: v0.5.1
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
  interval: 5m
  releaseName: chaos-mesh
  targetNamespace: chaos-mesh
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 10m
  values:
    customLabels:
      portefaix.xyz: v0.13.0

    controllerManager:
      # image: pingcap/chaos-mesh:v1.0.2
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 25m
          memory: 256Mi
    chaosDaemon:
      # image: pingcap/chaos-daemon:v1.0.2
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 256Mi
    dashboard:
      create: true
      # image: pingcap/chaos-dashboard:v1.0.2
      resources:
        limits:
          cpu: 100m
          memory: 1024Mi
        requests:
          cpu: 25m
          memory: 256Mi
      ingress:
        enabled: false
