---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: csi-secrets-store-provider-azure
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
  timeout: 3m
