apiVersion: v1
data:
    object-store.yaml: ENC[AES256_GCM,data:C0E7vgP9rheaCVa3jUEtjj4dInrI3b0ENsEVYIQMidTQo1aBEFdVZ7KPAw3TkblbxWYNCvpCdGINsLWlI6ITj82hYXN0zC2LwD9Pkbc9XSJXuMKsSwvHBWpWSd5MlGMNPXDxnjjan5Aw0cfO55G9eaS7k4fR5yyeheqRVvd8rvWQIjS9b1JHXUxAGPTheaKxl3hv22s3OpIZltLeISx4kHj9PLPQZeES8e6zgT/ZbWarBuLzp6pTByouSboySA7Qw5x8yf4xE1jSwJKnIAfHTRVKEf4Qi9BMR5m4rTFJSGHz3P1+9gciVuZH75JiUVA9Pe5VfiHI2JKGz4yL3wVWl7aNpwAU5cZIfNCZkZpcdJYPQyYTICKh45KcJLYS8q1O8U18T0lesUNb/L20Fszy3Cir8CFLWllp92f4n+WRhhOBbfiQTGnxrow58p63I9GKuOhsqAmJ9MsiqCI8dkNh9iqzilrGyGHjjg7myRhPXuq583QRcxap/kuLUeJth3zZqq8MQxMfeF/9t9zKCVX13lrL1U51Es0EWN/Ly9UT0861Jz3LTI71pVDgd+G1TBTPpjXZ7Tu3SNWtcvPddXALsMxDcL350qRjBVWhIZaV1rvgocNr4GE3SmmqBvgU1z6nhIEFid2UYTWPRgh2RFe3iMPFFGc8vDC+kY4U5fpZnHQFlkm/pny25lpVV9lQRJ7cEwwHgxxKBgJ1wvxXsbUHtDiOqqdkQV6imA/cAuAVj72RB75gqVJkZJ7D0+ryLU/whDFIkAd6iQFv/gSH0biZYDc1ImpmTfFu5bHJGrxRhXlFYQGCm+FgfMjcyGvhNRQ9wd+CXZAohhJWKD4PclnXV41f/8SlzszUipu3hqxMc1T6n8j2BWOit3YStLu97hTQLodAoUC6Pz+M5cj9RqVgo+C/3b+trePLA5FSOBjSzvx44GEIhl2heHbpdKRO16vt,iv:/VTJ3AlWH6kitMEVINexDYUpglYTfwo1jlDupafHhHY=,tag:TgjLZMIL2n5BLyYhRdK7+A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: thanos-objstore-config
    namespace: monitoring
sops:
    kms:
    -   arn: arn:aws:kms:eu-west-3:447241706233:key/cf77f24a-00db-4d6a-8b4b-a8dec3976ff2
        created_at: '2020-12-13T11:54:35Z'
        enc: AQICAHh+Ed4WL0Swc60FyM/gehqKyJmfUfIXKYrDBZTKtryeMAHWVVXUgvzGV9jTWMMW4e95AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJN7IRQl4tNtCx+5kAgEQgDulOsalfDd4fO93e6gkHVbplCDgpu8EFOwHgUHzu2971sglcflQsoj+oX6tAsJMZf1Cx/5Hwgdl0l5XjQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-13T11:54:35Z'
    mac: ENC[AES256_GCM,data:W9AEN9ivG99rvD2GKO81XLHADNnqaJabh2P5mx0BPzLDCbnXzoqLmUdLjIbD7U4NN194dMuX40HoPxQsPSh4MjLjVl5iAzQnGSToMbHfXlgdEvXRkg7gRg2LyLCFpQ8ZGAtShMYat6R/9oxjGjQJNp+V7UVyesccrhhrCxZvnkE=,iv:eOKu22GObOHlKAw6c0tdphHhZK7AJusQb9iCTSiB9pc=,tag:4gPnthKbtu+PL0jSKRvpOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.6.1
