---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  values:
    dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          nginx.ingress.kubernetes.io/auth-url: https://forwardauth.aws.portefaix.xyz/verify?uri=$scheme://$host$request_uri
          nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.aws.portefaix.xyz/?uri=$scheme://$host$request_uri"
        hosts:
          - chaos-mesh.aws.portefaix.xyz
        path: /
        tls:
          - secretName: chaos-mesh.aws.portefaix.xyz-tls
            hosts:
              - chaos-mesh.aws.portefaix.xyz
