---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  # chart:
  #   spec:
  #     version: 12.0.4
  values:
    alertmanager:
      serviceAccount:
        create: true
        name: alertmanager
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - alertmanager.cicd.portefaix.xyz
        path: /
      alertmanagerSpec:
        externalUrl: https://alertmanager.cicd.portefaix.xyz

    grafana:
      serviceAccount:
        create: true
        name: grafana
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - grafana.cicd.portefaix.xyz
        path: /

    prometheus:
      serviceAccount:
        create: true
        name: prometheus
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - prometheus.cicd.portefaix.xyz
        path: /
      prometheusSpec:
        externalUrl: https://prometheus.cicd.portefaix.xyz
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "standard"
              resources:
                requests:
                  storage: 1Gi
