---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/logging/loki
patchesStrategicMerge:
- chart-values-loki.yaml
# - chart-values-loki.yaml
# - chart-values-fluent-bit.yaml