---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-policy-agent
  namespace: flux-system
spec:
  interval: 24h
  url: https://open-policy-agent.github.io/gatekeeper/charts
  timeout: 3m
