# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  values:
    persistence:
      storageClass: nfs-client
      size: 20Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        # nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.0.0/16"
      hosts:
        - minio.192.168.1.114.nip.io
    resources:
      limits:
        cpu: 300m
        memory: 400Mi
      requests:
        cpu: 50m
        memory: 100Mi
    # existingSecret: minio-secret
    replicas: 1
    buckets:
      - name: portefaix-k3s-thanos
        policy: none
        purge: false
      - name: portefaix-k3s-loki
        policy: none
        purge: false
      - name: portefaix-k3s-tempo
        policy: none
        purge: false
      - name: portefaix-k3s-velero
        policy: none
        purge: false
      - name: portefaix-k3s-vector
        policy: none
        purge: false
