---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://fluent.github.io/helm-charts
      chart: fluent-bit
      version: 0.7.12
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  releaseName: fluent-bit
  targetNamespace: logging
  values:
    # image:
    #   repository: fluent/fluent-bit
    #   tag: 1.6.8
    serviceAccount:
      create: true
      name: fluent-bit
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack