---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: identity
spec:
  values:
    # image:
    #   repository: "pomerium/pomerium"
    #   tag: "v0.11.0"

    forwardAuth:
      enabled: true
      internal: false

    config:
      # routes under this wildcard domain are handled by pomerium
      rootDomain: gcp.portefaix.xyz
      insecure: false
      forceGenerateTLS: true
      forceGenerateSigningKey: true

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      
  valuesFrom:
    # - kind: ConfigMap
    #   name: prod-env-values
    - kind: Secret
      name: pomerium-values