---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: storage
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 5m
  releaseName: velero
  targetNamespace: storage
  # Depends on having the sealed secret to un-encrypted required secrets.
  # dependsOn:
  #   - name: sealed-secrets
  #     namespace: kube-system
  values:
    # image:
    #   repository: velero/velero
    #   tag: v1.5.2
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    serviceAccount:
      server:
        create: true
        name: velero
    metrics:
      enabled: true
      # todo(nlamirault) No ServiceMonitor in Chart ?
      # https://github.com/vmware-tanzu/velero/issues/2221
      # serviceMonitor:
      #   enabled: true
