# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: storage
spec:
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.23.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 5m
  releaseName: velero
  targetNamespace: storage
  # Depends on having the sealed secret to un-encrypted required secrets.
  # dependsOn:
  #   - name: sealed-secrets
  #     namespace: kube-system
  values:
    # TODO: https://github.com/vmware-tanzu/helm-charts/pull/281
    # customAnnotations:
    #   a8r.io/description: Backup and migrate Kubernetes applications and their persistent volumes
    #   a8r.io/owner: portefaix
    #   a8r.io/bugs: https://github.com/vmware-tanzu/velero/issues
    #   a8r.io/documentation: https://artifacthub.io/packages/helm/vmware-tanzu/velero
    #   a8r.io/repository: https://github.com/vmware-tanzu/velero
    #   a8r.io/support: https://github.com/vmware-tanzu/velero/issues
    # customLabels:
    #   portefaix.xyz/version: v0.16.0
    serviceAccount:
      server:
        create: true
        name: velero
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
