---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osm
  namespace: osm-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openservicemesh.github.io/osm
      chart: osm
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: osm
        namespace: flux-system
  releaseName: osm
  targetNamespace: osm-system
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  timeout: 10m
  values:
    OpenServiceMesh:
      enablePrometheus: false
      enableGrafana: false
      enableFluentbit: false
      deployJaeger: false
