---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:kms:eu-west-3:447241706233:key/cf77f24a-00db-4d6a-8b4b-a8dec3976ff2+arn:aws:iam::447241706233:role/portefaix-staging-eks-sops-eks"
  name: default
  namespace: flux-system
  
