---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:kms:eu-west-3:447241706233:key/80b36114-3fc2-4401-b5f2-dcd2a4b7e830+arn:aws:iam::447241706233:role/portefaix-staging-eks-sops-eks"
  name: default
  namespace: flux-system
  
