apiVersion: v1
data:
    object-store.yaml: ENC[AES256_GCM,data:uWKZVfYZ//MiR9Mx5SXzvtQKwBBQVmsmBeLbWWMz4QDDCSxjMCr82noQ5ktaAemfG+hK15KNLn/RQyJVslHX7FxWmKlaO/R/TCQk6+/wZTCoHJuLETkIelJ3PwtfJe8zMJFn8wHKGo+VMkQ9TWXXV7Slk+QbYWySXJpm6AaWE010SS1Silfgog/j77cr0m6umb3oPWRmiVnHmphdQ20gJPQBX9isM7Nlm3vTE1CnXkvox7eAZ/ROUH8o6r4+YUKm+wl4GZyj2NZkA1Zx54RzX6G3QD3fGyFUUSrmleT9/apRTIaF6Dnrm3XJLhzQYH/t6PRUE+qVvoR13LMtepVC8f/yaX+tn55X46cjXEbMlkSe55rjYyOaeJ3NolgOuGyfVOb/n6ZVkx424edBP/NsSnRJm7YaAf4tborc97sg/AKo5ABRKamkoBsiLEZT6teQ45LKnt4tB/xIgs18nuBgcWe4peMXl2roqNs4tV7cai+EW88vCmJZNJRtRoaM7iUVoRr9yzb4Y73oRf4FtwccRvqt2Y3eZf3rS80I0CwkGEOXB8RQl6ej8aqNvIEo4bNDbkV7rCheoPcQjqWGkKSPAwsNetOfNiPClaKowa1IGxJaaBlVRFXm19fhiCu7Fibkwm7i7mAlnQYTW6vDVu4S0VP6AJSb+GI4EGrZQwEBYRimhyM2HNouqZ3ITesSJwYSAXWLVkjO0nIpeySA6GB8VSuxZ/VD7LAqitPOlOknsNeQUS8zLsWEObs4zDKSmhRi58gKJzo36hWH44/2fYk6wYxsKq4MMbVKVpe4boKyBuHsTM9BNJGjdtFexDPgMij1TvyVhruTCfZ+utj119SxjDNfO8rO8YqNX1FdqO9RiDf42rndK5yMEY0V5DVc8Yk3te818T4yN0YXDVucHu9VVkRxmgLglLtGi4JfWxVrDAENl4AbkeVfVR41QFxJX6id,iv:SMoZGCRkAbE0GZYLgsLDnyluSHbeezZtxSCxNzyMWJA=,tag:Sc5Ufau8njJdjMuIFQeQDw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: thanos-objstore-config
    namespace: monitoring
sops:
    kms:
    -   arn: arn:aws:kms:eu-west-3:447241706233:key/80b36114-3fc2-4401-b5f2-dcd2a4b7e830
        created_at: '2020-12-20T08:22:27Z'
        enc: AQICAHgpAuVX23c1lBPSFpV4wlEZ/HqtVPRytquwFQ44f4BplAFwpiM4ASNB5raJVWk+v34nAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJGN2JRvvSHiEC/4OAgEQgDu3rcrsMfde1bn+4E56e/8LXnIb7ukJFEV2eCVPhThWchmlkYFqn9cEZJvdDnxB6stu6wHvNWe9bRq4Og==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-20T08:22:27Z'
    mac: ENC[AES256_GCM,data:8PQ+Umc0HBkvaDHQvYYWI298AQHa8agYx2sobyvO3L5GGzIKebISOjN57rAQgM0kvyj6xIbnLNW5O+a+GWuaPfQY4QNf9u4bhS3ugVV1W2T8/7cv41W9eSRZ+Ydt/bzMaJHVFZKnGe4Jpc1CiRk91Ky2EteusOHhLQ5HRv69MEA=,iv:QjCvyTngIIeH+f3mlxNYZdAQfXn7S/V+R+/JI8xeGIo=,tag:ht92RQqOdq61paoFVnJOQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.6.1
