---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- thanos-objstore-config.yaml
- ../../../../base/monitoring/kube-prometheus-stack
patchesStrategicMerge:
- chart-values.yaml
