---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.0.4
  # Depends on having the sealed secret to un-encrypted required secrets.
  # dependsOn:
  #   - name: sealed-secrets
  #     namespace: flux-system
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
    # extraArgs:
    #   - --enable-certificate-owner-ref=true
    #   - --dns01-recursive-nameservers=1.1.1.1:53
    #   - --dns01-recursive-nameservers-only
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack