---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: portefaix-prod-sops@portefaix-prod.iam.gserviceaccount.com
  name: default
  namespace: flux-system
  