---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../namespace
- ./kube-prometheus-stack.yaml
- ./prometheus-operator-mixin.yaml
- ./prometheus-mixin.yaml
- ./kube-state-metrics-mixin.yaml
- ./grafana-mixin.yaml
