config:
  ## https://docs.fluentbit.io/manual/service
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    error
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name            tail
        Path            /var/log/containers/*.log
        Parser          docker
        Tag             kube.*
        Mem_Buf_Limit   5MB
        Skip_Long_Lines On

    [INPUT]
        Name           systemd
        Tag            host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |

    [OUTPUT]
        name                   loki
        match                  *
        host                   loki
        port                   3100
        labels                 job=fluentbit
        label_keys             $sub['stream']
        auto_kubernetes_labels on

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name        docker_no_time
        Format      json
        Time_Keep   Off
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
