---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  values:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  valuesFrom:
    # - kind: ConfigMap
    #   name: prod-env-values
    - kind: Secret
      name: fluent-bit-values
