name: GCP / Inspec

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'
      tf_version:
        description: "Terraform version"
        required: true
        default: '0.14.0'

jobs:
  gcp_vpc:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Test Portefaix on GCP / ${{ github.event.inputs.env }}"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure GCP credentials
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 324.0.0
        # project_id: ${{ secrets.GCP_PROJECT_ID_PROD }}
        service_account_key: ${{ secrets.GCP_SA_KEY_PROD }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud info

    - name: "Install Chef Inspec"
      run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

    - name: "Run Infrastructure Tests"
      run: inspec exec test/my-profile --input-file test/my-profile/attributes.yml --reporter=cli html:./report.html --show-progress -t gcp://

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-report
        path: ./report.html
