# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: GCP / Tfsec

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - master
    paths:
      - "iac/gcp/**"
  pull_request:
    branches:
      - master
    paths:
      - "iac/gcp/**"

jobs:

  gcp_external_ips_cloud_nat:
    name: gcp-external-ips-cloud-nat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/external-ips/cloud-nat'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gcp_cloud_nat:
    name: gcp-cloud-nat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/cloud-nat'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gcp_cloud_dns:
    name: gcp-cloud-dns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/dns'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gcp_vpc:
    name: gcp-vpc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/vpc'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gcp_gke:
    name: gcp-gke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/gke'
        run: |
          make terraform-init SERVICE=iac/gcp/gke ENV=prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gcp_observability:
    name: gcp-observability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/observability'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  gcp_velero:
    name: gcp-velero
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan master
        uses: triat/terraform-security-scan@master
        with:
          tfsec_actions_working_dir: 'iac/gcp/velero'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
